### ISSUE TITLE
Lỗi khi chạy demo

### ISSUE THREAD

**Issue by vnlebaoduy** [pbcquoc/crnn#6]
Khi chạy demo mình bị lỗi như sau. Bạn có thể hướng mình chữa lỗi này được ko ạ. Mình cảm ơn
Cú pháp khi chạy
```
python demo.py --model checkpoints/netCRNN_100.pth  --alphabet data_old/char --img data_old/18449-2_10-4.jpg --imgW 1853 --imgH 128
```
```
Traceback (most recent call last):
  File "demo.py", line 46, in <module>
    preds = model(image)
  File "/home/leduy/anaconda3/envs/crnn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/leduy/Desktop/Project/crnn/models/crnn.py", line 78, in forward
    assert h == 1, "the height of conv must be 1"
AssertionError: the height of conv must be 1

```

**Comment by vnlebaoduy** [comment]
Lỗi: Do Sai Height. Mình đã sửa được
